version: '3.7'
services:
  db:
    container_name: bookstore-db
    image: postgres:15
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/database:/var/lib/postgresql/data